server:
  port: 9001
mybatis:
  type-aliases-package: net.sunnada.base.pojo
  mapper-locations: classpath:mapper/**/*.xml
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    url: jdbc:mysql://192.168.168.102:3307/tensquare_base?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: false
logging:
  level:
    net:
      sunnada:
        base:
          mapper: debug